"""Agent Studio — agents, teams, runs, tasks, approvals, triggers, keys, schedules, test cases, workspace files.

plans/AGENT-STUDIO-PLAN.md. Twelve ``studio_*`` tables plus two additions to
existing tables: ``chat_artifact.run_id`` (decision 24) and team-scoped memory
on ``user_memory`` (decision 22). Statuses are String + CHECK, never PgEnum,
so a new state is a one-line migration (the user_memory rationale).

Autogenerated against a scratch DB at 3f9aa289344c, then hand-edited: the
drift autogenerate wanted to apply to ``files`` column comments and
``ix_chat_estate_uid`` was removed (not ours), and the FK / CHECK changes on
the existing tables were written explicitly with names so the downgrade is
exact.

Revision ID: a5e7c9d1b3f2
Revises: 3f9aa289344c
Create Date: 2026-09-20 23:59:13.124626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e7c9d1b3f2'
down_revision: Union[str, Sequence[str], None] = '3f9aa289344c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_agent',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('length(name) > 0', name='ck_studio_agent_name_not_blank'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_studio_agent_name', 'studio_agent', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_studio_agent_workspace', 'studio_agent', ['tenant_id', 'workspace_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('studio_api_key',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_ids', postgresql.ARRAY(sa.UUID(as_uuid=False)), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('rate_limit_per_min > 0', name='ck_studio_api_key_rate_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_studio_api_key_workspace', 'studio_api_key', ['tenant_id', 'workspace_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('studio_team',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sensitive', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_to', postgresql.ARRAY(sa.UUID(as_uuid=False)), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('length(name) > 0', name='ck_studio_team_name_not_blank'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_studio_team_name', 'studio_team', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_studio_team_workspace', 'studio_team', ['tenant_id', 'workspace_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('studio_agent_version',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_gate_status', sa.String(length=16), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('published_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("test_gate_status <> 'overridden' OR override_reason IS NOT NULL", name='ck_studio_agent_version_override_reason'),
    sa.CheckConstraint("test_gate_status IN ('passed', 'overridden')", name='ck_studio_agent_version_gate'),
    sa.CheckConstraint('version >= 1', name='ck_studio_agent_version_positive'),
    sa.ForeignKeyConstraint(['agent_id'], ['studio_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_studio_agent_version')
    )
    op.create_table('studio_event_trigger',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('integration_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('health', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('poll', 'webhook')", name='ck_studio_event_trigger_source'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['integration.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['studio_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_studio_event_trigger_team', 'studio_event_trigger', ['team_id'], unique=False)
    op.create_table('studio_schedule',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('temporal_schedule_id', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['studio_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_studio_schedule_team', 'studio_schedule', ['team_id'], unique=False)
    op.create_table('studio_team_version',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roster_pins', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('test_gate_status', sa.String(length=16), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('published_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("test_gate_status <> 'overridden' OR override_reason IS NOT NULL", name='ck_studio_team_version_override_reason'),
    sa.CheckConstraint("test_gate_status IN ('passed', 'overridden')", name='ck_studio_team_version_gate'),
    sa.CheckConstraint('version >= 1', name='ck_studio_team_version_positive'),
    sa.ForeignKeyConstraint(['published_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['studio_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'version', name='uq_studio_team_version')
    )
    op.create_table('studio_run',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('team_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'planning'"), nullable=False),
    sa.Column('is_test', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trigger_kind', sa.String(length=16), nullable=False),
    sa.Column('trigger_actor_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('api_key_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('trigger_event_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workspace_prefix', sa.Text(), nullable=False),
    sa.Column('parent_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('fork_point_task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('budgets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planning', 'dispatching', 'waiting_approval', 'paused', 'finishing', 'completed', 'failed', 'cancelled')", name='ck_studio_run_status'),
    sa.CheckConstraint("trigger_kind IN ('chat', 'studio', 'api', 'schedule', 'event', 'test')", name='ck_studio_run_trigger_kind'),
    sa.CheckConstraint('parent_run_id IS NULL OR parent_run_id <> id', name='ck_studio_run_no_self_parent'),
    sa.ForeignKeyConstraint(['api_key_id'], ['studio_api_key.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['studio_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['studio_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_version_id'], ['studio_team_version.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporal_workflow_id')
    )
    op.create_index('ix_studio_run_parent', 'studio_run', ['parent_run_id'], unique=False)
    op.create_index('ix_studio_run_status', 'studio_run', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_studio_run_team_created', 'studio_run', ['tenant_id', 'team_id', 'created_at'], unique=False)
    op.create_table('studio_agent_task',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('agent_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('agent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('schema_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('files_written', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('depends_on', postgresql.ARRAY(sa.UUID(as_uuid=False)), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('budgets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sandbox_id', sa.String(length=255), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'waiting_approval', 'completed', 'error', 'budget_exhausted', 'stalled', 'schema_invalid', 'cancelled', 'approval_rejected')", name='ck_studio_agent_task_status'),
    sa.CheckConstraint('attempt >= 1', name='ck_studio_agent_task_attempt_positive'),
    sa.CheckConstraint('diagnostic IS NULL OR length(diagnostic) <= 4096', name='ck_studio_agent_task_diagnostic_cap'),
    sa.ForeignKeyConstraint(['agent_id'], ['studio_agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_version_id'], ['studio_agent_version.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['studio_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_studio_agent_task_run_status', 'studio_agent_task', ['run_id', 'status'], unique=False)
    op.create_table('studio_test_case',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject_kind', sa.String(length=8), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('assertions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_result', sa.String(length=16), server_default=sa.text("'never_run'"), nullable=False),
    sa.Column('last_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("last_result IN ('passed', 'failed', 'never_run')", name='ck_studio_test_case_last_result'),
    sa.CheckConstraint("subject_kind IN ('agent', 'team')", name='ck_studio_test_case_subject_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_run_id'], ['studio_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_studio_test_case_subject', 'studio_test_case', ['subject_kind', 'subject_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('studio_trigger_event',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trigger_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('poll', 'webhook')", name='ck_studio_trigger_event_source'),
    sa.ForeignKeyConstraint(['run_id'], ['studio_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['studio_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['studio_event_trigger.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'item_key', name='uq_studio_trigger_event_item')
    )
    op.create_index('ix_studio_trigger_event_trigger', 'studio_trigger_event', ['trigger_id', 'received_at'], unique=False)
    op.create_table('studio_approval',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('approver_ids', postgresql.ARRAY(sa.UUID(as_uuid=False)), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('decided_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('decided_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IS NULL OR outcome = 'unavailable' OR decided_at IS NOT NULL", name='ck_studio_approval_decided_at'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('allowed_once', 'rejected', 'cancelled', 'unavailable')", name='ck_studio_approval_outcome'),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['studio_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['studio_agent_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_studio_approval_pending', 'studio_approval', ['tenant_id', 'created_at'], unique=False, postgresql_where=sa.text('outcome IS NULL'))
    op.create_index('ix_studio_approval_run', 'studio_approval', ['run_id'], unique=False)
    op.create_table('studio_workspace_file',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('writer_task_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('promoted_artifact_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('indexed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT indexed OR promoted_artifact_id IS NOT NULL', name='ck_studio_workspace_file_indexed_promoted'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_studio_workspace_file_size'),
    sa.ForeignKeyConstraint(['promoted_artifact_id'], ['chat_artifact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['studio_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['writer_task_id'], ['studio_agent_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'path', name='uq_studio_workspace_file_path')
    )
    # -- Existing tables --------------------------------------------------
    # chat_artifact.run_id — a team run's output landing in chat links back to
    # its run (decision 24). SET NULL: the artifact outlives a purged run.
    op.add_column('chat_artifact', sa.Column('run_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key('fk_chat_artifact_run_id', 'chat_artifact', 'studio_run', ['run_id'], ['id'], ondelete='SET NULL')

    # user_memory — team scope (decision 22). scope='team' rows belong to a
    # Team (CASCADE); agent_id is provenance only (SET NULL).
    op.add_column('user_memory', sa.Column('team_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('user_memory', sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key('fk_user_memory_team_id', 'user_memory', 'studio_team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_memory_agent_id', 'user_memory', 'studio_agent', ['agent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('ck_user_memory_scope', 'user_memory', type_='check')
    op.create_check_constraint('ck_user_memory_scope', 'user_memory', "scope IN ('user', 'workspace', 'tenant', 'team')")
    op.create_check_constraint('ck_user_memory_team_scope_has_team', 'user_memory', "scope <> 'team' OR team_id IS NOT NULL")
    op.create_index('ix_user_memory_team', 'user_memory', ['tenant_id', 'team_id'], unique=False, postgresql_where=sa.text("scope = 'team' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_memory_team', table_name='user_memory')
    op.drop_constraint('ck_user_memory_team_scope_has_team', 'user_memory', type_='check')
    op.drop_constraint('ck_user_memory_scope', 'user_memory', type_='check')
    op.create_check_constraint('ck_user_memory_scope', 'user_memory', "scope IN ('user', 'workspace', 'tenant')")
    op.drop_constraint('fk_user_memory_agent_id', 'user_memory', type_='foreignkey')
    op.drop_constraint('fk_user_memory_team_id', 'user_memory', type_='foreignkey')
    op.drop_column('user_memory', 'agent_id')
    op.drop_column('user_memory', 'team_id')
    op.drop_constraint('fk_chat_artifact_run_id', 'chat_artifact', type_='foreignkey')
    op.drop_column('chat_artifact', 'run_id')
    op.drop_table('studio_workspace_file')
    op.drop_index('ix_studio_approval_run', table_name='studio_approval')
    op.drop_index('ix_studio_approval_pending', table_name='studio_approval', postgresql_where=sa.text('outcome IS NULL'))
    op.drop_table('studio_approval')
    op.drop_index('ix_studio_trigger_event_trigger', table_name='studio_trigger_event')
    op.drop_table('studio_trigger_event')
    op.drop_index('ix_studio_test_case_subject', table_name='studio_test_case', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('studio_test_case')
    op.drop_index('ix_studio_agent_task_run_status', table_name='studio_agent_task')
    op.drop_table('studio_agent_task')
    op.drop_index('ix_studio_run_team_created', table_name='studio_run')
    op.drop_index('ix_studio_run_status', table_name='studio_run')
    op.drop_index('ix_studio_run_parent', table_name='studio_run')
    op.drop_table('studio_run')
    op.drop_table('studio_team_version')
    op.drop_index('ix_studio_schedule_team', table_name='studio_schedule')
    op.drop_table('studio_schedule')
    op.drop_index('ix_studio_event_trigger_team', table_name='studio_event_trigger')
    op.drop_table('studio_event_trigger')
    op.drop_table('studio_agent_version')
    op.drop_index('ix_studio_team_workspace', table_name='studio_team', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_studio_team_name', table_name='studio_team', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('studio_team')
    op.drop_index('ix_studio_api_key_workspace', table_name='studio_api_key', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('studio_api_key')
    op.drop_index('ix_studio_agent_workspace', table_name='studio_agent', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_studio_agent_name', table_name='studio_agent', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('studio_agent')
    # ### end Alembic commands ###
